module.exports = {
    BASE_URL: 'http://6342-2406-7400-92-63fc-00-102.ngrok.io/',
    LABTEST: 'testinfo',
    PACKAGETEST: 'packageinfo',
    testsInfo: {address: '', dateSlot: '', test_type: '', timeSlot: ''},
    tests: [],
    profileInfo: {phone: '', name: '', email: '', dob: '', gender: "0", password: "", searchPinCode: "", familyRef: ''},
    token: '',
    currentLoc: [],
    editLoc: [],
    familyInfo: {phone: '', name: '', email: 'test@test.com', dob: '', gender: "0", password: "1234", searchPinCode: "", familyRef: ''},
    labtest: 0,
    package: 1,
    medicalcenter: 2,
    changeCartView: true,
    familyName: '',
    familyMob: '',
    chosenPincode: '',
    day: 0,
    week: 1,
    month: 2,
    year: 3,
    editAppntId: ''
}